// Copies the shared vanilla-JS runtimes (game engine, app renderer) into a TS module the
// native app can import. The same files power the web app's Code Mode and exported pages.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const shared = resolve(here, "../../shared/runtime");
const out = resolve(here, "../src/generated/runtime.ts");
mkdirSync(dirname(out), { recursive: true });
const engine = readFileSync(resolve(shared, "engine.js"), "utf8");
const app = readFileSync(resolve(shared, "app.js"), "utf8");
writeFileSync(
  out,
  `// Generated by scripts/sync-runtime.mjs — do not edit.\nexport const ENGINE_JS = ${JSON.stringify(engine)};\nexport const APP_JS = ${JSON.stringify(app)};\n`,
);
console.log("synced runtime ->", out);
